/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexionBD.ConexionBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.Usuario;

/**
 *
 * @author Herrera
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public static String user = "";
    
    public VentanaLogin() {
        
        ConexionBD.getConexion();
        
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        messagePane.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        txtIniciarSesion = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        cajaPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        messagePane = new javax.swing.JPanel();
        txtMessageLogin = new javax.swing.JLabel();
        btnCloseMesaggePane = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JPanel();
        txtLogin1 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        txtLogo = new javax.swing.JLabel();
        cuadroDec = new javax.swing.JPanel();
        cuadroDec2 = new javax.swing.JPanel();
        btnHomePane = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        btn_minimize = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtOlvidoXD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(55, 42, 104));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txtIniciarSesion.setForeground(new java.awt.Color(100, 100, 100));
        txtIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIniciarSesion.setText("INICIAR SESION");
        loginPane.add(txtIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, 30));

        btnLogin.setBackground(new java.awt.Color(52, 156, 244));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin.setText("LOGIN");
        btnLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        loginPane.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 120, 30));

        cajaUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cajaUsuario.setForeground(new java.awt.Color(50, 50, 50));
        cajaUsuario.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 280, 30));

        txtUser.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(50, 50, 50));
        txtUser.setText("username");
        loginPane.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 70, 30));

        cajaPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaPassword.setForeground(new java.awt.Color(50, 50, 50));
        cajaPassword.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 280, 30));

        txtPassword.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtPassword.setText("password");
        loginPane.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, 30));

        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        loginPane.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 440, -1));

        messagePane.setForeground(new java.awt.Color(33, 235, 103));
        messagePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messagePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagePaneMouseClicked(evt);
            }
        });
        messagePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMessageLogin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtMessageLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtMessageLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messagePane.add(txtMessageLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 340, 50));

        btnCloseMesaggePane.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btnCloseMesaggePane.setForeground(new java.awt.Color(240, 240, 240));
        btnCloseMesaggePane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseMesaggePane.setText("X");
        btnCloseMesaggePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseMesaggePane.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messagePane.add(btnCloseMesaggePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        loginPane.add(messagePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 440, 50));

        jPanel1.setBackground(new java.awt.Color(52, 156, 244));
        loginPane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 10));

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtLogin1.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin1.setText("RESET");
        btnReset.add(txtLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        loginPane.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, 30));

        bg.add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 550));

        menu.setBackground(new java.awt.Color(40, 23, 72));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        txtLogo.setForeground(new java.awt.Color(240, 240, 240));
        txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogo.setText("AutAmi");
        menu.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 140, 50));

        cuadroDec.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout cuadroDecLayout = new javax.swing.GroupLayout(cuadroDec);
        cuadroDec.setLayout(cuadroDecLayout);
        cuadroDecLayout.setHorizontalGroup(
            cuadroDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        cuadroDecLayout.setVerticalGroup(
            cuadroDecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        menu.add(cuadroDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 30, 30));

        cuadroDec2.setBackground(new java.awt.Color(8, 117, 207));

        javax.swing.GroupLayout cuadroDec2Layout = new javax.swing.GroupLayout(cuadroDec2);
        cuadroDec2.setLayout(cuadroDec2Layout);
        cuadroDec2Layout.setHorizontalGroup(
            cuadroDec2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        cuadroDec2Layout.setVerticalGroup(
            cuadroDec2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        menu.add(cuadroDec2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 30, 30));

        btnHomePane.setBackground(new java.awt.Color(22, 16, 44));
        btnHomePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHomePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(btnHomePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 250, 50));

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 720));

        barra.setBackground(new java.awt.Color(55, 42, 104));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btn_minimize.setForeground(new java.awt.Color(240, 240, 240));
        btn_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimize.setText("–");
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        barra.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        btn_close.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btn_close.setForeground(new java.awt.Color(240, 240, 240));
        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setText("X");
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        barra.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        bg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        jPanel2.setBackground(new java.awt.Color(42, 31, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOlvidoXD.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtOlvidoXD.setForeground(new java.awt.Color(240, 240, 240));
        txtOlvidoXD.setText("olvidaste la contraseña? preguntale a tu jefe XD");
        jPanel2.add(txtOlvidoXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 300, 50));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 1030, 50));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xMouse, yMouse;
    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    Usuario usuario = new Usuario();

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        char[] arrayC = cajaPassword.getPassword();
        String pass = new String(arrayC);

        if (!cajaUsuario.getText().trim().equals("") && !pass.trim().equals("")) {
            usuario.setUsuario(cajaUsuario.getText());
            usuario.setPassword(pass);
            ResultSet rs = ConexionBD.verificarUsuario(usuario);

            try {
                rs.next();
                if (rs.getString(1) != null) {
                    user = rs.getString(1);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VentanaInicio().setVisible(true);
                        }
                    });
                    dispose();
                } else {
                    messagePane.setBackground(new Color(199, 56, 87));
                    txtMessageLogin.setText("DATOS ERRONEOS intenta de nuevo");
                    messagePane.setVisible(true);
                }

            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        } else {
            String noDatos = "Introduce [";

            if (cajaUsuario.getText().trim().equals("")) {
                noDatos += " USUARIO";
            }

            if (pass.trim().equals("")) {
                noDatos += " PASSWORD";
            }

            noDatos += " ]";

            messagePane.setBackground(new Color(199, 56, 87));
            txtMessageLogin.setText(noDatos);
            messagePane.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void messagePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePaneMouseClicked
        messagePane.setVisible(false);
    }//GEN-LAST:event_messagePaneMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        restablecerComponentes(cajaUsuario, cajaPassword);
    }//GEN-LAST:event_btnResetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }
    
    
    public void restablecerComponentes(JComponent... componentes) {
        for (JComponent c : componentes) {

            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            } else if (c instanceof JCheckBox) {
                ((JCheckBox) c).setSelected(false);
            } else if (c instanceof JComboBox) {
                ((JComboBox) c).setSelectedIndex(0);
            } else if (c instanceof JSpinner) {
                ((JSpinner) c).setValue(0);
            } else if (c instanceof JPasswordField) {
            ((JPasswordField) c).setText("");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnCloseMesaggePane;
    private javax.swing.JPanel btnHomePane;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnReset;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JPanel cuadroDec;
    private javax.swing.JPanel cuadroDec2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel messagePane;
    private javax.swing.JLabel txtIniciarSesion;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtLogin1;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtMessageLogin;
    private javax.swing.JLabel txtOlvidoXD;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
