/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import conexionBD.ConexionBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.Usuario;

/**
 *
 * @author Herrera
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();
        messagePane.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        txtIniciarSesion = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        cajaPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        messagePane = new javax.swing.JPanel();
        txtMessageLogin = new javax.swing.JLabel();
        btnCloseMesaggePane = new javax.swing.JLabel();
        btnCloseMesaggePane1 = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        btn_minimize = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        txtOlvidoXD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(72, 58, 125));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txtIniciarSesion.setForeground(new java.awt.Color(70, 70, 70));
        txtIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIniciarSesion.setText("INICIAR SESION");
        loginPane.add(txtIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 440, 30));

        btnLogin.setBackground(new java.awt.Color(153, 0, 153));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin.setText("LOGIN");
        btnLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 140, 40));

        loginPane.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 180, 40));

        cajaUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cajaUsuario.setForeground(new java.awt.Color(50, 50, 50));
        cajaUsuario.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 280, 30));

        txtUser.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(50, 50, 50));
        txtUser.setText("username");
        loginPane.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 70, 30));

        cajaPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaPassword.setForeground(new java.awt.Color(50, 50, 50));
        cajaPassword.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 280, 30));

        txtPassword.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtPassword.setText("password");
        loginPane.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 60, 30));

        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        loginPane.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 440, -1));

        messagePane.setForeground(new java.awt.Color(33, 235, 103));
        messagePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messagePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagePaneMouseClicked(evt);
            }
        });
        messagePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMessageLogin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtMessageLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtMessageLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messagePane.add(txtMessageLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 340, 50));

        btnCloseMesaggePane.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btnCloseMesaggePane.setForeground(new java.awt.Color(240, 240, 240));
        btnCloseMesaggePane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseMesaggePane.setText("X");
        btnCloseMesaggePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseMesaggePane.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messagePane.add(btnCloseMesaggePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        btnCloseMesaggePane1.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btnCloseMesaggePane1.setForeground(new java.awt.Color(240, 240, 240));
        btnCloseMesaggePane1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseMesaggePane1.setText("X");
        btnCloseMesaggePane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseMesaggePane1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messagePane.add(btnCloseMesaggePane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 30, 30));

        loginPane.add(messagePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 440, 50));

        bg.add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 550));

        barra.setBackground(new java.awt.Color(72, 58, 125));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btn_minimize.setForeground(new java.awt.Color(240, 240, 240));
        btn_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimize.setText("–");
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        barra.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        btn_close.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btn_close.setForeground(new java.awt.Color(240, 240, 240));
        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setText("X");
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        barra.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        bg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        txtOlvidoXD.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtOlvidoXD.setForeground(new java.awt.Color(240, 240, 240));
        txtOlvidoXD.setText("olvidaste la contraseña? preguntale a tu jefe XD");
        bg.add(txtOlvidoXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, -1, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xMouse, yMouse;
    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    Usuario usuario = new Usuario();

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        char[] arrayC = cajaPassword.getPassword();
        String pass = new String(arrayC);

        if (!cajaUsuario.getText().equals("") && !pass.equals("")) {
            usuario.setUsuario(cajaUsuario.getText());
            usuario.setPassword(pass);

            ConexionBD.getConexion();

            ResultSet rs = ConexionBD.consultarUsuario(usuario);

            try {
                if (rs.next()) {

                    if (rs.getInt(1) == 1) {
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                new VentanaInicio().setVisible(true);
                            }
                        });
                        dispose();
                    } else {
                        messagePane.setBackground(new Color(199, 56, 87));
                        txtMessageLogin.setText("DATOS ERRONEOS intenta de nuevo");
                        messagePane.setVisible(true);
                    }

                }
            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        } else {
            String noDatos = "Introduce [";

            if (cajaUsuario.getText().equals("")) {
                noDatos += " USUARIO";
            }

            if (pass.equals("")) {
                noDatos += " PASSWORD";
            }

            noDatos += " ]";

            messagePane.setBackground(new Color(199, 56, 87));
            txtMessageLogin.setText(noDatos);
            messagePane.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void messagePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePaneMouseClicked
        messagePane.setVisible(false);
    }//GEN-LAST:event_messagePaneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnCloseMesaggePane;
    private javax.swing.JLabel btnCloseMesaggePane1;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPanel messagePane;
    private javax.swing.JLabel txtIniciarSesion;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtMessageLogin;
    private javax.swing.JLabel txtOlvidoXD;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
