/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Herrera
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        txtIniciarSesion = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        cajaUsername = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        cajaPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        btn_minimize = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        txtOlvidoXD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(72, 58, 125));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 28)); // NOI18N
        txtIniciarSesion.setForeground(new java.awt.Color(70, 70, 70));
        txtIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIniciarSesion.setText("INICIAR SESION");
        loginPane.add(txtIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 30));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin.setText("LOGIN");
        btnLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 50));

        loginPane.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 290, 50));

        cajaUsername.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        cajaUsername.setForeground(new java.awt.Color(50, 50, 50));
        cajaUsername.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 350, 50));

        txtUser.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(50, 50, 50));
        txtUser.setText("username");
        loginPane.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 30));

        cajaPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cajaPassword.setForeground(new java.awt.Color(50, 50, 50));
        cajaPassword.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 350, 50));

        txtPassword.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtPassword.setText("password");
        loginPane.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 30));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        loginPane.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        bg.add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 500, 600));

        barra.setBackground(new java.awt.Color(72, 58, 125));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_minimize.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btn_minimize.setForeground(new java.awt.Color(240, 240, 240));
        btn_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimize.setText("–");
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        barra.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        btn_close.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btn_close.setForeground(new java.awt.Color(240, 240, 240));
        btn_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_close.setText("X");
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });
        barra.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        bg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 30));

        txtOlvidoXD.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        txtOlvidoXD.setForeground(new java.awt.Color(240, 240, 240));
        txtOlvidoXD.setText("olvidaste la contraseña? preguntale a tu jefe XD");
        bg.add(txtOlvidoXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 680, -1, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xMouse, yMouse;
    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaUsername;
    private javax.swing.JPanel loginPane;
    private javax.swing.JLabel txtIniciarSesion;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtOlvidoXD;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
